[project]
name = "PySide Widgets Project"
requires-python = ">=3.12.13"

[tool.pyside6-project]
files = [
	"main.py",
	"ui/__init__.py",
	"ui/designer/form.ui",
	"ui/designer/alphabet_lesson.ui",
	"ui/designer/alphabet_menu.ui",
	"ui/designer/lesson_select.ui",
	"ui/designer/spell_lesson.ui",
	"ui/designer/spell_category.ui",
	"ui/designer/spell_word.ui",
	"ui/designer/word_lesson.ui",
	"ui/designer/word_menu.ui",
	"ui/designer/login.ui",
	"ui/designer/register.ui",
	"ui/generated/__init__.py",
	"ui/generated/ui_form.py",
	"ui/generated/ui_alphabet_lesson.py",
	"ui/generated/ui_alphabet_menu.py",
	"ui/generated/ui_lesson_select.py",
	"ui/generated/ui_spell_category.py",
	"ui/generated/ui_spell_lesson.py",
	"ui/generated/ui_spell_word.py",
	"ui/generated/ui_word_lesson.py",
	"ui/generated/ui_word_menu.py",
	"backend/__init__.py",
	"backend/config.py",
	"backend/content_data.py",
	"backend/recognition_engine.py",
	"backend/session_state.py",
	"backend/auth_service.py",
	"database/__init__.py",
	"menus/__init__.py",
	"menus/alphabet_menu.py",
	"menus/lesson_select.py",
	"menus/spell_select.py",
	"menus/word_menu.py",
	"games/__init__.py",
	"lessons/__init__.py",
	"lessons/alphabet_lesson.py",
	"lessons/spell_lesson.py",
	"lessons/word_lesson.py",
	"screens/__init__.py",
	"screens/app_controller.py",
	"screens/auth/login.py",
	"screens/auth/register.py",
	"screens/dashboard/dashboard.py",
	"screens/auth/__init__.py",
	"screens/dashboard/__init__.py",
	"screens/profile/__init__.py",
	"screens/achievements/__init__.py",
]
